le75/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap


admin.autodiscover()


urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from filer.fields.image import FilerImageField
from ckeditor.fields import RichTextField
from cms.models.pluginmodel import CMSPlugin


AUDIENCE_CHOICES = (
    (1, _("BAC 1")),
    (2, _("BAC 2")),
    (3, _("BAC 3")),
)
SEMESTER_CHOICES = (
    (1, _("Q1")),
    (2, _("Q2")),
    (3, _("Q1 and Q2")),
)

LANGUAGE_CHOICES = (
    (1, _("French")),
    (2, _("English")),
    (3, _("Dutch")),
)

YEAR_CHOICES = (
    (2015, "2015-2016"),
    (2016, "2016-2017"),
    (2017, "2017-2018"),
    (2018, "2018-2019"),
    (2019, "2019-2020"),
    (2020, "2020-2021"),
    (2021, "2021-2022"),
)

class TeachingUnit(models.Model):
    is_published =  models.BooleanField(verbose_name=_("is published?"))
    name = models.CharField(max_length=250, verbose_name=_("course official name"))
    common_name = models.CharField(max_length=50, verbose_name=_("course common name"), blank=True)
    slug = models.SlugField(unique=True, verbose_name=_("slug"), help_text=_("Unique identifier. Allows a constant targeting of this person"))
    ue = models.PositiveIntegerField()
    year = models.IntegerField(default=2015, choices=YEAR_CHOICES, verbose_name=_("academic year"))
    audience = models.PositiveSmallIntegerField(choices=AUDIENCE_CHOICES, verbose_name=_("audience"))
    orientation = models.ManyToManyField("Orientation", verbose_name=_("orientation"))
    course_type = models.ManyToManyField("CourseType", verbose_name=_("course type"))
    category = models.ManyToManyField("Category", verbose_name=_("category"))
    semester = models.PositiveSmallIntegerField(choices=SEMESTER_CHOICES, verbose_name=_("semester"))
    hours = models.PositiveSmallIntegerField(verbose_name=_("hours"))
    ects = models.PositiveSmallIntegerField(verbose_name=_("ects"))

    def __str__(self):
        return self.name

    def teacher_list(self):
        teachers = []
        for course in self.course_set.all():
            for teacher in course.teachers.all():
                if teacher not in teachers:
                    teachers.append(teacher)
        return teachers

    class Meta:
        verbose_name = _("TeachingUnit")
        verbose_name_plural = _("TeachingUnits")
        ordering = ["-year", "ue"]

    def get_absolute_url(self):
        return reverse('teaching-unit-detail', kwargs={'slug': self.slug})


class Course(models.Model):
    teaching_unit = models.ForeignKey(TeachingUnit, verbose_name=_("teaching unit"))
    teachers = models.ManyToManyField("Teacher", verbose_name=_("teachers"))
    is_mandatory = models.BooleanField(verbose_name=_("mandatory?"))
    co_required = RichTextField(verbose_name=_("co-required courses"), blank=True)
    pre_required = RichTextField(verbose_name=_("pre-required"), blank=True)
    goals = RichTextField(verbose_name=_("goals"))
    outcomes = RichTextField(verbose_name=_("learning outcomes"))
    methodology = RichTextField(verbose_name=_("methodology"))
    content = RichTextField(verbose_name=_("content"), blank=True)
    evaluation_mode = RichTextField(verbose_name=_("evaluation mode"))
    evaluation_criterias = RichTextField(verbose_name=("evaluation criterias"))
    language = models.PositiveSmallIntegerField(choices=LANGUAGE_CHOICES, verbose_name=_("teaching and evaluation language"))
    references = RichTextField(verbose_name=_("potential sources, references and materials"), blank=True)

    def __str__(self):
        return self.teaching_unit.name

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

    def get_absolute_url(self):
        return reverse('teaching-unit-detail', kwargs={'slug': self.teaching_unit.slug})


class Orientation(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("name"))
    slug = models.CharField(max_length=50, verbose_name=_("slug"))

    class Meta:
        verbose_name = _("Orientation")
        verbose_name_plural = _("Orientations")
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('orientation-detail', kwargs={'slug': self.slug})

    def get_teachers(self):
        teachers = []
        for ue in self.teachingunit_set.all():
            for course in ue.course_set.all():
                for teacher in course.teachers.all():
                    if teacher not in teachers:
                        teachers.append(teacher)
        return teachers


class CourseType(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Course type")
        verbose_name_plural = _("Course types")
        ordering = ["name"]


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("category name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Course category")
        verbose_name_plural = _("Course categories")
        ordering = ["name"]


class Teacher(models.Model):
    firstname = models.CharField(max_length=50, verbose_name=_("first name"))
    lastname = models.CharField(max_length=50, verbose_name=_("last name"))
    slug = models.CharField(max_length=100, verbose_name=_("slug"), null=True)
    department = models.ForeignKey("Department", related_name=("teacher_department"), null=True)
    role = models.CharField(max_length=100, verbose_name=_("role"))
    responsibilities = models.TextField(verbose_name=_("responsibilities"), blank=True)
    email = models.EmailField(verbose_name=_("email"), blank=True)
    phonenumber = models.CharField(max_length=20, verbose_name=_("phone number"), blank=True)
    website = models.URLField(verbose_name=_("website"), blank=True)
    bio = RichTextField(verbose_name=_("short biography"), blank=True)
    image = FilerImageField(null=True, blank=True, related_name="teacher_image", verbose_name=_("picture"))

    def __str__(self):
        return u"%s %s" % (self.lastname, self.firstname)

    class Meta:
        verbose_name = _("Staff member")
        verbose_name_plural = _("Staff members")
        ordering = ["lastname", "firstname"]

    def get_absolute_url(self):
        return reverse('teacher-detail', kwargs={'slug': u"%s" % self.slug})


class Department(models.Model):
    name = models.CharField(max_length=50, verbose_name=_("name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Working Department")
        verbose_name_plural = _("Working Departments")
        ordering = ["name"]


class OrientationPluginModel(CMSPlugin):
    orientation = models.ForeignKey(Orientation, verbose_name=_("orientation"))

course/views.py
from course.models import TeachingUnit, Teacher, Orientation
from django.views.generic.detail import DetailView


class OrientationDetailView(DetailView):
    model = Orientation


class TeachingUnitDetailView(DetailView):
    model = TeachingUnit


class TeacherDetailView(DetailView):
    model = Teacher

course/templates/course/orientation_detail.html
{% extends "base.html" %}


{% load cms_tags %}


{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}
<article>
    <header class="main__content__header">
        <h1>{{ object.name }}</h1>
    </header>

    {% placeholder "content" %}
</article>
{% endblock content %}

course/templates/course/teacher_detail.html
{% extends "base.html" %}


{% load cms_tags custom_tags thumbnail %}


{% block title %}{% page_attribute "page_title" %}{% endblock title %}


{% block content %}
<article>
    <header class="main__content__header">
        <h1>{% render_model object "firstname" %} {% render_model object "lastname" %}</h1>
        <p class="subhead">{% render_model object "role" %}</p>
    </header>

    {% if object.department.name or object.email or object.phonenumber or object.website %}
    <dl class="course--metadata column--small">
        {% if object.department.name %}
        <dt>Département</dt>
        <dd>{{ object.department.name }}</dd>
        {% endif %}

        {% if object.email %}
        <dt>Email</dt>
        <dd>{{ object.email|html_encode_email|safe }}</dd>
        {% endif %}

        {% if object.phonenumber and object.phonenumber != "0"%}
        <dt>Téléphone</dt>
        <dd>{{ object.phonenumber }}</dd>
        {% endif %}

        {% if object.website %}
        <dt>Site internet</dt>
        <dd><a href="{{ object.website }}">{{ object.website }}</a></dd>
        {% endif %}
    </dl>
    {% endif %}

    <p>{{ object.responsibilities }}</p>
    
    <p>
        {% thumbnail object.image 105x105 as portrait %}
        {% if portrait %}<img class="portrait" src="{{ portrait.url }}" />{% endif %}
        {{ object.bio|safe|default:"Aucune bio" }}
    </p>

    {% if object.course_set.all %}
    <h2 class="heading-2">Cours</h2>
    {% regroup object.course_set.all|dictsort:"teaching_unit.name"|dictsort:"teaching_unit.audience" by teaching_unit.audience as audience_list %}

    <ul class="zigzag column column--small">
        {% for audience in audience_list %}
        <li class="audience-list">BAC {{ audience.grouper }}
            <ul class="course-list">
                {% for course in audience.list %}
                <li><a href="{{ course.get_absolute_url }}">{{ course }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
    {% endif %}
</article>
{% endblock content %}

course/templates/course/teachingunit_detail.html
{% extends "base.html" %}
{% load cms_tags custom_tags%}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
<article>
    <header class="main__content__header">
        <h1>{% render_model object "name" %}</h1>
        <p class="subhead">{{ object.get_year_display }} &mdash; UE {% render_model object "ue" %} {% if object.common_name %}: {% render_model object "common_name" %}{% endif %}</p>
    </header>

    <dl class="course--metadata column--big">
        <dt>Audience</dt>
        <dd>BAC {{ object.audience }}</dd>


        <dt>Orientations</dt>
        {% for orientation in object.orientation.all %}
            <dd>{{ orientation }}</dd>
        {% endfor %}
        
        <dt class="separator">Type de cours</dt>
        {% for course_type in object.course_type.all %}
            <dd>{{ course_type }}</dd>
        {% endfor %}

        <dt>Catégories</dt>
        {% for category in object.category.all %}
            <dd>{{ category }}</dd>
        {% endfor %}

        <dt class="separator">Semestre</dt>
        <dd>{{ object.get_semester_display }}</dd>
        
        <dt>Heures</dt>
        <dd>{{ object.hours }} heures</dd>
        
        <dt>Crédits</dt>
        <dd>{{ object.ects }} ECTS</dd>
        
        <dt class="separator">Requis?</dt>
        <dd>{{ object.course_set.all.first.is_mandatory|yesno:"Cours obligatoire, Cours à option" }}</dd>
        
        <dt>Langue</dt>
        <dd>en {{ object.get_language_display|default:"français" }}</dd>
        
        <dt class="teacher-list">par</dt>
            {% for teacher in object.teacher_list|dictsort:"lastname" %}
                <dd class="teacher-list-item"><a href="{{ teacher.get_absolute_url }}">{{ teacher.firstname }} {{ teacher.lastname }}</a></dd>
            {% endfor %}
        </dd>
    </dl>

    {% for course in object.course_set.all %}
    <div class="course--description column column--big">
        {% if course.co_required %}
            <div class="course--description--section">
                <h2 class="heading-2">Co-requis</h2>
                {{ course.co_required|safe }}
            </div>
        {% endif %}
        
        {% if course.pre_required %}
            <div class="course--description--section">
                <h2 class="heading-2">Pré-requis</h2>
                {{ course.pre_required|safe }}
            </div>
        {% endif %}
        
        {% if course.goals %}
            <div class="course--description--section">
                <h2 class="heading-2">Objectifs</h2>
                {{ course.goals|safe }}
            </div>
        {% endif %}
        
        {% if course.outcomes %}
            <div class="course--description--section">
                <h2 class="heading-2">Acquis d’apprentissage</h2>
                {{ course.outcomes|safe }}
            </div>
        {% endif %}
        
        {% if course.methodology %}
            <div class="course--description--section">
                <h2 class="heading-2">Méthode</h2>
                {{ course.methodology|safe }}
            </div>
        {% endif %}

        {% if course.content %}
            <div class="course--description--section">
                <h2 class="heading-2">Contenu</h2>
                {{ course.content|safe }}
            </div>
        {% endif %}
        
        {% if course.evaluation_mode %}
            <div class="course--description--section">
                <h2 class="heading-2">Mode d’évaluation</h2>
                {{ course.evaluation_mode|safe }}
            </div>
        {% endif %}
        
        {% if course.evaluation_criterias %}
            <div class="course--description--section">
                <h2 class="heading-2">Critères d’évaluation</h2>
                {{ course.evaluation_criterias|safe }}
            </div>
        {% endif %}

        {% if course.references %}
            <div class="course--description--section">
                <h2 class="heading-2">Sources et références indicatives</h2>
                {{ course.references|safe }}
            </div>
        {% endif %}
    </div>
    {% endfor %}
</article>
{% endblock content %}